fix: use simple-peer fork that does not throw when setting error codes
Uses a [temporary fork](https://github.com/ipfs-shipyard/simple-peer)
of simple-peer with https://github.com/feross/simple-peer/pull/686
applied so it does not throw when trying to override the `.code` property
of [DOMExceptions](https://developer.mozilla.org/en-US/docs/Web/API/DOMException)

Fixes these sorts of errors:

```
        Error: Uncaught TypeError: Cannot assign to read only property 'code' of object '' (file:/home/travis/build/libp2p/js-libp2p-webrtc-star/node_modules/simple-peer/index.js:26)
```